pipeline:
    name: payment-service1
    identifier: paymentservice1
    allowStageExecutions: false
    projectIdentifier: bootcampciAngelCarrasco
    orgIdentifier: Angel_Carrasco
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: githubctsering
                repoName: harness-cie-lab
                build: <+input>
    stages:
        - stage:
              name: Build
              identifier: Build
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.bootcampgkecluster
                          namespace: payment-service-build
                  execution:
                      steps:
                          - step:
                                type: RunTests
                                name: runTestsWithIntelligence
                                identifier: runTestsWithIntelligence
                                spec:
                                    connectorRef: account.bootcampdockerhub
                                    image: nikpap/mvn-openjdk-8:harness
                                    language: Java
                                    buildTool: Maven
                                    args: test
                                    packages: com.nikp
                                    runOnlySelectedTests: true
                                    preCommand: cd payment-service
                                    reports:
                                        type: JUnit
                                        spec:
                                            paths:
                                                - "**/*.xml"
                                    resources:
                                        limits:
                                            memory: 2Gi
                                            cpu: "2"
